#!/usr/bin/env bash

#
# this script is run by root, on every boot
#

# initial configuration
SCRIPT_PATH=$(readlink -f "$0")			# save path to this script
BASE="/usr/share/mahalia-utils"			# the base folder for the project
CONF="/etc/mahalia/config"			# the location of the configuration file
SOUNDCARD_CONF="/etc/mahalia/cape4all.alsactl.state" # the location of the soundcard configuration file
source $BASE/functions.sh			# include bash functions
source $CONF					# include config file

# tell user what is happening
echo "[mahalia-setup] Setting up soundcard settings"

# set permissions of LED
chmod 777 $MAHALIA_LED/trigger

# turn LED off
echo none > $MAHALIA_LED/trigger

# set dma interrupt thread to FIFO priorty 95
set_irq_priority_ff "edma_ccint" 95

# restore soundcard settings
alsactl restore -f $SOUNDCARD_CONF
